### ISSUE TITLE
Empty image src attribute

### ISSUE THREAD

**Issue by jonerd** [janrembold/jquery-responsive-image#10]
When a requested source file for a specific resolution is not available the image src attribute is empty and no image is displayed. I would prefer a fallback to refer to the next available source with lower or higher resolution.

**Comment by janrembold** [comment]
@jonerd What kind of unavailability do you mean? Wrong image path? Server down? Or didn't match any query?

**Comment by jonerd** [comment]
@janrembold I mean if the image does not exist for a specific resolution. For example when the image with resolution 480p isn't available (because the source just doesn't exist) I would expect the plugin to fall back to the default image source, e.g. 240p

**Comment by janrembold** [comment]
Fixed with https://github.com/janrembold/jquery-responsive-image/pull/15
